title: Live A Hero Wiki
url: https://liveahero-wiki.github.io
github_edit: https://github.com/liveahero-wiki/liveahero-wiki.github.io/edit/master
permalink: /news/:year/:month/:title/
timezone: Asia/Tokyo
date_format: "%-d %b %Y %R JST"
markdown: kramdown
excerpt_separator: "<!--more-->"
#kramdown:
#  parse_block_html: true
sass:
  style: compressed
plugins:
  #- jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "charas"
    values:
      unreleased: false
  - scope:
      type: "events"
    values:
      layout: event
  - scope:
      path: "assets/img/fg"
    values:
      fg: true
  - scope:
      path: "assets"
    values:
      sitemap: false

collections:
  charas:
    output: true
  events:
    output: true
    sort_by: event_start_time

exclude:
  - readme.md
  - CONTRIBUTING.md